# fly.toml app configuration file generated for verirule-worker on 2026-02-10T14:23:45Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'verirule-worker'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile'

[env]
  VERIRULE_MODE = 'worker'

[processes]
  worker = 'python -m app'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
